Vagrant.configure(2) do |config|
	config.vm.define "epuakhaw1754centos7ans" do |epuakhaw1754centos7ans|
		epuakhaw1754centos7ans.vm.box = "centos/7"
		epuakhaw1754centos7ans.vm.hostname = "epuakhaw1754centos7ans"
		config.disksize.size = '20GB'
		epuakhaw1754centos7ans.vm.network "public_network",
			use_dhcp_assigned_default_route: true
			epuakhaw1754centos7ans.vm.provision "shell", path: "scripts/install.sh"
			epuakhaw1754centos7ans.vm.provider "virtualbox" do |v|
			v.name = "epuakhaw1754centos7ans"
			v.memory = 512
			v.cpus = 1
	  end
	end
	config.vm.define "epuakhaw1754ubuntu16ans" do |epuakhaw1754ubuntu16ans|
		epuakhaw1754ubuntu16ans.vm.box = "ubuntu/xenial64"
		epuakhaw1754ubuntu16ans.vm.hostname = "epuakhaw1754ubuntu16ans"
		config.disksize.size = '20GB'
		epuakhaw1754ubuntu16ans.vm.network "public_network",
			use_dhcp_assigned_default_route: true
		epuakhaw1754ubuntu16ans.vm.provision "shell", path: "scripts/install.sh"
		epuakhaw1754ubuntu16ans.vm.provider "virtualbox" do |v|
			v.name = "epuakhaw1754ubuntu16ans"
			v.memory = 512
			v.cpus = 1
	  end
	end
	config.vm.define "epuakhaw1754ubuntu16ansible" do |epuakhaw1754ubuntu16ansible|
		epuakhaw1754ubuntu16ansible.vm.box = "ubuntu/xenial64"
		epuakhaw1754ubuntu16ansible.vm.hostname = "epuakhaw1754ubuntu16ansible"
		config.disksize.size = '20GB'
		epuakhaw1754ubuntu16ansible.vm.network "public_network",
			use_dhcp_assigned_default_route: true
			epuakhaw1754ubuntu16ansible.vm.provision "shell", path: "scripts/install.sh"
			epuakhaw1754ubuntu16ansible.vm.provider "virtualbox" do |v|
			v.name = "epuakhaw1754ubuntu16ansible"
			v.memory = 512
			v.cpus = 1
	  end
	end

end